services:
  Regression:
    image: shaarv70/appium
    environment:
      - APPIUM_PORT=4723
      - TEST_SUITE=master.xml
      - DEVICE_PORT=${DEVICE_PORT}
    networks:
      - test-network
    ports:
      - "4723:4723"
    deploy:
      replicas: 0
    volumes:
      - ./RemoteServerlogs:/home/appium-docker/RemoteServerLog
      - ./output/Regression:/home/appium-docker/extent-test-output
      - ./output/Regression:/home/appium-docker/test-output

  Release:
    image: shaarv70/appium
    environment:
      - APPIUM_PORT=4724
      - TEST_SUITE=master.xml
      - DEVICE_PORT=${DEVICE_PORT}
    networks:
      - test-network
    ports:
      - "4724:4724"
    deploy:
      replicas: 0
    volumes:
      - ./RemoteServerlogs:/home/appium-docker/RemoteServerLog
      - ./output/Release:/home/appium-docker/extent-test-output
      - ./output/Release:/home/appium-docker/test-output

networks:
  test-network:
    driver: bridge

x-environment-variables:
  COMPOSE_HTTP_TIMEOUT: 300
